version: "3.9"
services:
  rails:
    build: .
    container_name: rails
    command: bundle exec puma -C config/puma.rb -e production # Productionモードで起動
    volumes:
      - .:/myapp
      - public-data:/myapp/public

      # nginxの設定で使用している
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log

      - /myapp/node_modules
    env_file:
      - .env
    depends_on:
      - db
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker

    # Railsをrootユーザーで起動(コンテナが作成したファイルを編集することがないのでrootにする(compile時のエラー対策))
    user: root

  # Webpackerは本番では利用しません。WebpackerはJavascriptやCSSをコードを書いてくれたらすぐにコンパイルして読み込んでくれる用途で利用しています。
  # webpacker:
  #   build: .
  #   volumes:
  #     - .:/myapp
  #     - /myapp/node_modules
  #     - public-data:/myapp/public
  #   command: ./bin/webpack-dev-server
  #   environment:
  #     WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  #   ports:
  #     - "3035:3035"
  #   user: root

  db:
    image: mysql:8.0.27
    container_name: db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - rails

volumes:
  db:
    driver: local
  # bundleは不要だったので消しておきます
  # bundle:
  #   driver: local
  public-data:
  tmp-data:
  log-data:
